### ISSUE TITLE
Windows support/Multiple Displays

### ISSUE THREAD

**Issue by koshisan** [subraizada3/27gn950controller#2]
Hi!

Thanks for (potentially) saving us all from having to rely in LG's software department!

I am trying to run control.py on Windows. However, I do get an error message:

`raceback (most recent call last):
  File "control.py", line 35, in <module>
    dev = usb.core.find(idVendor=0x043e, idProduct = 0x9a8a)
  File "C:\Users\koshi\AppData\Local\Programs\Python\Python38\lib\site-packages\usb\core.py", line 1299, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available`

Which is not correct - In fact there are even two backends available, since I am running two LG27GN950 ;)

I am not really sure if the script is supposed to be running on Windows at all - but if it did and if it were to support multiple monitors, it could do more than LGs software, which is refusing any kind of control at all when running in a multiple monitor setup...

**Comment by dmitrii-galantsev** [comment]
I believe he hasn't tested with windows.

**Comment by subraizada3** [comment]
That error is for PyUSB not being able to find an interface to communicate with the OS's (Windows's) USB subsystem.

I booted into my Windows installation and these steps were sufficient to make it work:

- I installed Python from python.org => Downloads => there's a download button in the popup when you hover over the downloads button in the navigation bar

- I opened a command prompt and ran `py -m pip install pyusb` to install the PyUSB library

Now the libusb backend needs to be installed.

- I downloaded the latest release from [https://github.com/libusb/libusb/releases](https://github.com/libusb/libusb/releases). The first asset, `libusb-1.0.24.7z` contains the correct files.

- For some reason libusb distributes their Windows version as a 7zip file instead of a normal zip file, so if you don't already have 7zip you'll need to install it from [https://www.7-zip.org/download.html](https://www.7-zip.org/download.html). The second download link, for the 64-bit x64 exe should work.

- Then, open your downloads folder, right click the libusb 7z file you downloaded, and extract it.

- From the extracted files, go into the `VS2019` folder and then into the `MS64` folder and then into the `dll` folder. In here is a file called `libusb-1.0.dll`. Copy that dll into `C:\Windows\System32`.

- Run the control.py file again and it should work now.

I did make a minor code update to control.py to make it Windows compatible so you'll need to update the copy you have.

I don't own two of these monitors, would be interested in seeing how it works for you.

**Comment by koshisan** [comment]
Wow! Thank you very much - I indeed didn't realize that pyusb had further dependencies not installed by pip. I did install libusb and updated the the code.

I can confirm that it now does work on windows! However, it does only work on one monitor.

Unfortunately I never did anything in python the script would probably either need to provide a selection which "dev" object should be used or apply everything to all "dev" objects found.

In my opinion that should depend on if you plan to implement options to sync the screen/set colors in the future.

Especially video sync only really makes sense on one display.

(Did you ever figure out how to realize that? I checked if it would be able to grab the screen content at all at from python at a fast enough pace, but the trick seems to be to just take a screenshot and scale it down: https://github.com/digital-concrete/light-sync)

On the other hand selectable displays would add more complexity to running the script non-interactively (which I would really love to see - because that would make it possible to integrate the lights into my smarthome setup), since at least two arguments would have to be parsed...

Like I said I am not really familiar with python, but if I can help debugging, etc. I am all in for it!

**Comment by subraizada3** [comment]
I added multimonitor support. Obviously I can't test it, but it should work. See the readme for information.
I also added a noninteractive mode.

For video sync, see issue #1. I don't know how the protocol encodes the color information, and it seems nontrivial to figure that out.

**Comment by koshisan** [comment]
Thanks again for your work! Unfortunately that seems to have broken something:

 File "control.py", line 52, in <module>
    dev.set_configuration()
  File "C:\Users\koshi\AppData\Local\Programs\Python\Python38\lib\site-packages\usb\core.py", line 905, in set_configuration
    self._ctx.managed_set_configuration(self, configuration)
  File "C:\Users\koshi\AppData\Local\Programs\Python\Python38\lib\site-packages\usb\core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Users\koshi\AppData\Local\Programs\Python\Python38\lib\site-packages\usb\core.py", line 158, in managed_set_configuration
    self.managed_open()
  File "C:\Users\koshi\AppData\Local\Programs\Python\Python38\lib\site-packages\usb\core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Users\koshi\AppData\Local\Programs\Python\Python38\lib\site-packages\usb\core.py", line 131, in managed_open
    self.handle = self.backend.open_device(self.dev)
  File "C:\Users\koshi\AppData\Local\Programs\Python\Python38\lib\site-packages\usb\backend\libusb1.py", line 804, in open_device
    return _DeviceHandle(dev)
  File "C:\Users\koshi\AppData\Local\Programs\Python\Python38\lib\site-packages\usb\backend\libusb1.py", line 652, in __init__
    _check(_lib.libusb_open(self.devid, byref(self.handle)))
  File "C:\Users\koshi\AppData\Local\Programs\Python\Python38\lib\site-packages\usb\backend\libusb1.py", line 604, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 5] Input/Output Error

If I comment out the part causing the error it says that two monitors are detected - so that part seems to work

**Comment by subraizada3** [comment]
Does everything else (e.g. actually controlling the lighting) work properly with line 52 commented out?

**Comment by koshisan** [comment]
No, it gives the same error on "cfg = dev.get_active_configuration() # TODO: is this necessary? cfg is unused."

It only starts when I completely disable lines 51-53 - but that doesn't get me very far:

C:\AutoHotkey>python control.py
Found 2 monitors
TurnOn
invalid command
TurnOff
invalid command
h
Traceback (most recent call last):
  File "control.py", line 245, in <module>
    launchCli()
  File "control.py", line 174, in launchCli
    cliProcess(text)
  File "control.py", line 139, in cliProcess
    print(helpstring)
NameError: name 'helpstring' is not defined

**Comment by subraizada3** [comment]
I've pushed an update which prints some debug info. If you could paste the output from that into something like pastebin.com and share the URL, that would be helpful.

**Comment by koshisan** [comment]
Of course! https://pastebin.com/j6B8TGJj

**Comment by subraizada3** [comment]
It seems that libusb is unable to read the properties of or communicate with the second monitor. For example, the information printed for the first monitor has:
```
 iManufacturer          :    0x1 LG Electronics Inc.
 iProduct               :    0x3 LG UltraGear Monitor
 iSerialNumber          :    0x4 104NTJJJD828
```
And for the second monitor it has:
```
 iManufacturer          :    0x1 Error Accessing String
 iProduct               :    0x3 Error Accessing String
 iSerialNumber          :    0x4 Error Accessing String
```

At this point there are two things that I have left to suggest. 1:

- Exit out of the LG control software from your taskbar if it's running, and uninstall the LG software.
- Download Zadig, a USB driver installer, from [https://zadig.akeo.ie/](https://zadig.akeo.ie/).
- Open Zadig, in the Options menu at the top click 'List All Devices'
- Select the LG monitor from the list. It'll show a 'HidUsb' driver on the left; go ahead and replace it with WinUSB.

![image](https://user-images.githubusercontent.com/3249268/123026557-622dc580-d3aa-11eb-8e67-502c93bad552.png)

- Do that for both monitors. They should now show up in device manager (right click the start menu icon => 5th option). In my case, it's at the very bottom. Maybe also re-plug their USB just to be on the safe side.

![image](https://user-images.githubusercontent.com/3249268/123026626-8093c100-d3aa-11eb-9d8c-345717654ef6.png)

Then you can run control.py again and hopefully it'll work. If not, you can double click the device in Device Manager, go to the Driver tab and Roll Back the drivers, which will undo the modifications from Zadig and allow the LG control center to work again.

Or, the very final thing I can suggest, is that you could also try using the libusb-win32 backend instead of the libusb1 backend which you currently have. Roll back the drivers, then from `C:\Windows\System32`, delete the `libusb-1.0.dll` to uninstall the libusb1 backend. From [https://sourceforge.net/projects/libusb-win32/files/libusb-win32-releases/1.2.6.0/](https://sourceforge.net/projects/libusb-win32/files/libusb-win32-releases/1.2.6.0/) download `libusb-win32-devel-filter-1.2.6.0.exe`, run it to install LibUSB, then run the filter wizard and install the device filter for the LG UltraGear monitor device. Try control.py again; if it still doesn't work then you can run the filter wizard again to remove the libusb device filters and then rollback the drivers from Device Manager.

For me with one monitor it works in all three configurations (the existing libusb1 backend, the Zadig WinUSB drivers, and with the libusb-win32 backend). But unfortunately I don't really know why this is happening, and if none of that fixes it then I don't know where to go from there. Good luck!

**Comment by koshisan** [comment]
Big thanks! Replacing the drivers did work!

I am now able to use every function currently implemented!

Btw: LG control is also still working - I suspect that most functions work over DDC instead of USB. I spend a few hours the other day trying to trick the Ultragear software into recognizing only one display with DDC manipulation - until I realized it just refuses to work in _any_ multi display configuration - regardless if both of them are LG...
So my best guess right now is that only Ultragear requires USB for the light setup.

Btw: Did you see my reply to #1? I bet it's just a prefix and a color code for every individual LED...

**Comment by subraizada3** [comment]
Awesome! So you can control both or individual monitors? And did you have to use the Zadig/WinUSB drivers or the libusb-win32 drivers? I can update the documentation with that information.

**Comment by koshisan** [comment]
Yes - I can control them both or individually - everything works as intented. 
I am using the WinUSB driver (default setting of Zadig)

**Comment by subraizada3** [comment]
Thanks. I wrote up a Windows setup guide ([here](https://github.com/subraizada3/27gn950controller/blob/master/windows-setup.md)) and linked it from the readme. Hopefully that'll help other people in the future.

I also deleted a line from control.py that I believe is completely unnecessary, and has no effect on the functionality or operation of the program. But it was related to the part of the code causing some of the issues you were having, so let me know if the latest version causes any issues and I'll add it back in.

Aside from that, this issue seems to be fully resolved. Feel free to give a ping back here if you release any software/code for this monitor for your smart home control project.

**Comment by koshisan** [comment]
Still working :) One interesting find though: Running LG OnScreen Control seems to block access to the USB devices - but only sometimes. It was working fine earlier, after returning to the office (and powercycling the monitors inbetween) I got:

C:\AutoHotkey>python control.py turnOn
Traceback (most recent call last):
  File "control.py", line 66, in <module>
    dev.set_configuration()
  File "C:\Users\koshi\AppData\Local\Programs\Python\Python38\lib\site-packages\usb\core.py", line 905, in set_configuration
    self._ctx.managed_set_configuration(self, configuration)
  File "C:\Users\koshi\AppData\Local\Programs\Python\Python38\lib\site-packages\usb\core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Users\koshi\AppData\Local\Programs\Python\Python38\lib\site-packages\usb\core.py", line 158, in managed_set_configuration
    self.managed_open()
  File "C:\Users\koshi\AppData\Local\Programs\Python\Python38\lib\site-packages\usb\core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Users\koshi\AppData\Local\Programs\Python\Python38\lib\site-packages\usb\core.py", line 131, in managed_open
    self.handle = self.backend.open_device(self.dev)
  File "C:\Users\koshi\AppData\Local\Programs\Python\Python38\lib\site-packages\usb\backend\libusb1.py", line 804, in open_device
    return _DeviceHandle(dev)
  File "C:\Users\koshi\AppData\Local\Programs\Python\Python38\lib\site-packages\usb\backend\libusb1.py", line 652, in __init__
    _check(_lib.libusb_open(self.devid, byref(self.handle)))
  File "C:\Users\koshi\AppData\Local\Programs\Python\Python38\lib\site-packages\usb\backend\libusb1.py", line 604, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 5] Input/Output Error

After closing the LG software everything runs fine again - just in case anyone is asking!

Thank you for your help today! There will probably no code released for my smarthome project, since it is not "real" software development work but more hacking everything together with IOTLink (software for windows remote control), MQTT, Node-red and OpenHab. Once setting the colors/synchronization works, I can use it to integrate the monitors into my normal light scenes...
